version: '3'
services:
  magic-supplies:
    build: .
    hostname: magic-supplies
    environment:
     - JAVA_OPTS=-Xmx256m -Xms128m
    ports:
     - "8080:8080"
    depends_on:
     - "magic-broker"
  magic-broker:
    hostname: magic-broker
    image: "rmohr/activemq:5.14.3-alpine"
    ports:
     - "61616:61616"
     - "8161:8161"
  hawtio:
    hostname: event-ops
    image: "indigo/hawtio"
    ports:
     - "8090:8090"       